[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.develop]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.develop.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENABLEGITINFO = "true"
