backend:
  name: git-gateway
  branch: main
media_folder: static/imgs
public_folder: /imgs
collections:
  - name: "notes"
    label: "Notes"
    folder: "/content/notes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}--{{hour}}-{{minute}}-{{second}}Z--{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
          format: "YYYY-MM-DDTHH:mm:ssZ",
        }
      - { label: "Slug", name: "slug", widget: "string", required: true }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, min: 1 }
      - { label: "Type", name: "type", widget: "string", default: "notes" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - {
          label: "Theme collapse section",
          name: "bookCollapseSection",
          widget: "boolean",
          required: true,
          default: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
